# Current server public network IP Or IP for local testing and Port
server: 127.0.0.1
server_port: 1081
# Discontinuation time after no request
timeout: 40


# Supported authentication methods                             支持的认证方式 ， 这边服务程序只支持一种验证方式，需要在二者中选择
# 0 Represents that validation is not required                 表示无验证
# 2 Indicates that account password verification is required   表示进行账号密码认证
authority_method: 2

users:
  -
    username: bard
    password: bard1234
  -
    username: bard2
    password: bard21234


## Debugging Open Switch and Switch of Logging System
## default： false
debug: false
slog: true